version: "3.8"

services:
  snx:
    image: galileo/snx
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /lib/modules:/lib/modules
      - ./firefox:/root/.mozilla/
    environment:
      - DISPLAY=${DISPLAY}
    cap_add:
      - NET_ADMIN
    networks:
      snx-network:
        ipv4_address: ${LOCAL_IP}
networks:
  snx-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GW_IP}
