#!/bin/bash

MPROFILE=/root/.mozilla

if [ ! -f $MPROFILE/firefox/installs.ini ]; then
    echo "creating firefox profile"
    cp -a /fake/.mozilla /root
fi

/usr/bin/cshell/launcher

/scripts/monitor-gw &

/scripts/monitor-routing &

exec &>/dev/null
firefox
